model:
  source: huggingface
  repo_id: HauhauCS/Gemma-4-E2B-Uncensored-HauhauCS-Aggressive
  filename: Gemma-4-E2B-Uncensored-HauhauCS-Aggressive-Q6_K_P.gguf
  direct_url: ''
  gdrive_file_id: ''
  hf_token_env: HF_TOKEN
  local_dir: ./models
  verify_sha256: false
  sha256: ''
  mmproj_enabled: true
  mmproj_repo_id: HauhauCS/Gemma-4-E2B-Uncensored-HauhauCS-Aggressive
  mmproj_filename: mmproj-Gemma-4-E2B-Uncensored-HauhauCS-Aggressive-f16.gguf
  mmproj_sha256: ''
  mmproj_gdrive_file_id: ''
llama_cpp:
  repo_url: https://github.com/ggml-org/llama.cpp.git
  branch: master
  build_dir: ./llama.cpp
  cuda_arch: '75'
  jobs: 4
  prebuilt_gdrive_file_id: ''
server:
  host: 0.0.0.0
  port: 8084
  gpu: 1
  api_key: ''
  webui: false
  jinja: true
  webui_mcp_proxy: false
  n_gpu_layers: -1
  ctx_size: 32768
  ctx_size_min: 0
  batch_size: 2048
  ubatch_size: 512
  threads: 2
  threads_batch: 4
  tensor_split: '1'
  split_mode: layer
  parallel: 1
  cont_batching: true
  rope_scaling: none
  rope_freq_base: 0
  rope_freq_scale: 0
  cache_type_k: q8_0
  cache_type_v: q8_0
  log_file: ./logs/llama-server_8084.log
tunnel:
  provider: cloudflare
  ngrok_token_env: NGROK_AUTHTOKEN
  ngrok_domain: '28dcb02c7bfa-1965096042333252791.ngrok-free.app'
  cloudflare_token: ''
  cloudflare_domain: ''
mcp:
  enabled: false
